[toolchain]
anchor_version = "1.0.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow_q2_2026 = "d5Yda6GmqiHgyhf9skzY3ffFRu3Ku9hhqNEToPguytW"
withelist_q2_2026 = "AsyYG7z3cNhF2rszsC96iNoZTdKwq4QhoSa9K3WgaSxp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ANCHOR_IDL_DIR=$PWD/target/idl yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
testsvm = "cargo test"

[hooks]
