[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_gpt_tuktuk = "9Qq5wSMFCAFSL6W4dtpgbfwqcjSd1UaiuXVmepSGDVKt"

[programs.localnet]
solana_gpt_tuktuk = "9Qq5wSMFCAFSL6W4dtpgbfwqcjSd1UaiuXVmepSGDVKt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-node test.ts"
