[package]
name = "anchor-escrow-q2-2026"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "anchor_escrow_q2_2026"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"

[dev-dependencies]
litesvm = "0.9.0"
litesvm-token = "0.9.0"
solana-account = "3.4.0"
solana-address = "2.6.0"
solana-instruction = "3.1.0"
solana-keypair = "3.1.0"
solana-message = "3.0.1"
solana-program-pack = "3.0.0"
solana-pubkey = "3.0.0"
solana-rpc-client = "2.2.1"
solana-signer = "3.0.0"
solana-transaction = "3.0.2"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }
